services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fairgiveaway-backend
    ports:
      - "80:7860"
    env_file:
      - .env
    restart: unless-stopped
